# Generated by Django 5.2.7 on 2025-11-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('color', models.CharField(default='#cccccc', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('periodico', 'Periodico'), ('podcast', 'Podcast'), ('television', 'Television'), ('radio', 'Radio')], max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('web', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesgoEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango_min', models.FloatField()),
                ('rango_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SesgoEnfoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SesgoIdeologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango_min', models.FloatField()),
                ('rango_max', models.FloatField()),
                ('color', models.CharField(default='#999999', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comparativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('claves', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('objetividad', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comparativas/')),
                ('destacada', models.BooleanField(default=False)),
                ('categoria', models.ManyToManyField(to='appContraPunto.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('fecha', models.DateField()),
                ('enlace', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('sesgo_ideologico', models.FloatField(blank=True, null=True)),
                ('sesgo_emocional', models.FloatField()),
                ('comparativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='appContraPunto.comparativa')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appContraPunto.medio')),
                ('sesgo_enfoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appContraPunto.sesgoenfoque')),
            ],
        ),
    ]
