# Generated by Django 5.2.7 on 2025-12-09 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContraPunto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_actualidad', models.CharField(max_length=300)),
                ('opciones_actualidad', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('posturas', models.JSONField()),
                ('fecha_publicacion', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='comparativa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('periodico', 'Periodico'), ('podcast', 'Podcast'), ('television', 'Television'), ('radio', 'Radio'), ('revista', 'Revista')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='RespuestaFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_actualidad', models.CharField(max_length=1)),
                ('es_correcta', models.BooleanField()),
                ('respuesta_postura', models.CharField(max_length=1)),
                ('sesgo_visibilidad', models.IntegerField()),
                ('tipo_info_valiosa', models.CharField(max_length=20)),
                ('resumen_usuario', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appContraPunto.encuestaflash')),
            ],
        ),
    ]
