# Generated by Django 5.2.7 on 2025-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContraPunto', '0002_encuestaflash_alter_categoria_icono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaflash',
            name='tipo_info_valiosa',
            field=models.JSONField(default=list),
        ),
    ]
