# Generated by Django 5.2.7 on 2025-12-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContraPunto', '0003_alter_respuestaflash_tipo_info_valiosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaflash',
            name='tipo_info_valiosa',
            field=models.CharField(max_length=20),
        ),
    ]
